require_extension('B');
int len = (RS2 >> 24) & 15;
int off = (RS2 >> 16) & 31;
int roff = -off & 31;
len = len ? len : 16;
reg_t mask = (1 << len) - 1;
reg_t data = zext32(RS2);
mask = (mask << off) | (mask >> roff);
data = (data << off) | (data >> roff);
WRITE_RD(sext32((data & mask) | (RS1 & ~mask)));
