#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

rm -rf build

mkdir build
cd build
mkdir install
CFLAGS="-Werror -Wall -Wextra -Wvla"
CXXFLAGS="-Wnon-virtual-dtor $CFLAGS"
CXXFLAGS="$CXXFLAGS" CFLAGS="$CFLAGS" $DIR/../configure --prefix=`pwd`/install
make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)"
make check
make install install-hdrs-list.h

# check that help message prints without error
install/bin/spike -h
