include $(TARGETDIR)/spike/device/Makefile_common.inc
RUN_CMD = $(TARGET_SIM) $(TARGET_FLAGS) --isa=rv64im \
        +signature=$(*).signature.output +signature-granularity=4\
        $< 

RUN_TARGET=\
	$(RUN_CMD) 

